on:
  push:
    branches:
      - master
      - proposal
      - fix-ci
  pull_request:
    branches:
      - master
      - proposal

name: compile

env:
  TL_PACKAGES: adjustbox algorithmicx algorithms biber biblatex biblatex-gb7714-2015 bibtex booktabs caption carlisle cases catchfile chinese-jfm chngcntr cleveref collectbox ctex dvips enumitem environ extarrows fancybox fancyhdr fancyvrb float framed fvextra gbt7714 gsftopk helvetic hologo ifplatform lastpage latexmk lineno minted multirow mwe natbib needspace newtx nth oberdiek pdftexcmds realscripts rsfs setspace siunitx subfig tcolorbox texcount texliveonfly threeparttable threeparttablex times titling tocloft trimspaces txfonts ucs upquote was xcolor xecjk xpatch xstring zhnumber

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: [-xelatex, -lualatex]
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: compile LaTeX document
        uses: xu-cheng/texlive-action/full@v1
        with:
          run: |
            make ENGINE=${{ matrix.compiler }} all
            mv main.pdf linux${{ matrix.compiler }}.pdf
      - name: check compile
        if: ${{ failure() }}
        run: |
          cat main.log
      - name: upload pdf
        uses: actions/upload-artifact@v2
        with:
          name: document linux output
          path: linux${{ matrix.compiler }}.pdf
